# Generated by Django 6.0.1 on 2026-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_arrears_student_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='UPI',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='assessment_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
