# Generated by Django 6.0.1 on 2026-01-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_upi_student_assessment_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
