# Generated by Django 6.0.1 on 2026-01-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_student_course_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emergency_contact',
            new_name='Parent_contact',
        ),
    ]
